api:
  port: 8801
interpreter:
  #  interpreterActivityConfig:
  #    disableSystemSearchAttributes: true # set to true if you don't have advanced visibility in Cadence, see more https://github.com/uber/cadence/issues/5085
  cadence:
    hostPort: 127.0.0.1:7833
    domain: default
  defaultWorkflowConfig:
    continueAsNewThreshold: 100