name: Temporal/Cadence 2-in-1 Integration Test
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Cadence/Temporal environment"
        run: docker compose -f docker-compose/ci-cadence-temporal-dependencies.yml up -d
      - name: "Test against cadence/temporal"
        run: make ci-cadence-temporal-integ-test
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3