name: Cadence Integration Test
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up cadence environment"
        run: docker compose -f docker-compose/ci-cadence-dependencies.yml up -d
      - name: "Test against cadence"
        run: make ci-cadence-integ-test
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
